### ISSUE TITLE
MediaPipe Issue

### ISSUE THREAD

**Issue by nelsonalbertohj** [ihp-lab/OpenSense#18]
I am trying to build a simple pipeline that implements LibreFace, but I cannot get MediaPipe (which is required to work  with libreface) to work on the OpenSense.WPF.exe release version 3.1.0.0

I first got the following error. It seems like the MediaPipe component cannot reach the file specified in the Settings/Graph   for the MediaPipe component.
<img width="311" alt="image" src="https://github.com/ihp-lab/OpenSense/assets/51930759/bc3b92a2-d598-4084-b5b0-f1bff4597679">

I am able to fix this first error by changing the file path under MediaPipe Settings/Graphs to an absolute path, but then I get the following error (which seems to have to do with MediaPipe not finding a path again)
![image](https://github.com/ihp-lab/OpenSense/assets/51930759/40c8e851-0320-4c60-9147-9c9b35fe7d57)

I'd appreciate any suggestions on how to troubleshoot this.

**Comment by KanaHayama** [comment]
It has been a long time since the last time I configure our MediaPipe, so I may remember it wrong. In our LibreFace, we only use the face_landmark model, and we are not using the face_detection model. So, I do not remember whether that model actually works. Since I included it into the build, that means this model should work.
Can you tell me why you want to use this model?

**Comment by nelsonalbertohj** [comment]
Thank you for the response! I assumed that in the OpenSense WPF app, using MediaPipe was required because of the following. Is there a work-around to this or maybe a specific .pipe file that already implements libreface in OpenSense? I could not find this in the current documentation

<img width="769" alt="image" src="https://github.com/ihp-lab/OpenSense/assets/51930759/6830afdd-9770-4092-99f6-64e543304939">

My intended use for this is to test the real-time potential  use of libreface for research purposes, as I hope to use libreface models later to analyze affective video data

**Comment by KanaHayama** [comment]
[20230825__LibreFace__Injector__AzureKinect.pipe.zip](https://github.com/ihp-lab/OpenSense/files/12812848/20230825__LibreFace__Injector__AzureKinect.pipe.zip)
Here is a pipeline configuration file that I use. You can modify and try it.

**Comment by nelsonalbertohj** [comment]
Thank you for forwarding this. When I try to run it, I get the same exact issue as before. The one associated with MediaPipe. Do I need to have installed something else in my computer before running MediaPipe? I am using the exact same configuration you sent (and it seems like the software is not able to find the Graph path because as seen in the error message, the error has to do with System.IO.DirectoryNotFoundException because the software is trying to find the MediaPipe .pbtxt in 'C:/Windoes/system32/" rather than in the mediapipe directory inside "/OpenSense WPF Application 3.1.0/")
<img width="738" alt="image" src="https://github.com/ihp-lab/OpenSense/assets/51930759/5749fa23-a9af-4512-abbe-ddee3e3f7c70">
![image](https://github.com/ihp-lab/OpenSense/assets/51930759/694b39e8-305a-4bc8-8153-2572990d0643)

**Comment by nelsonalbertohj** [comment]
Indeed, that seems to have been the issue, once I copy/pasted the mediapipe folder from OpenSense WPF Application 3.1.0 to my "C:/Windows/system32/", things started working

**Comment by KanaHayama** [comment]
By default, it should be ok to just use that relative path. Though some machines have different settings of the order folders to lookup files. However, in your case you can use it by changing it to an absolute path, I think that is enough.

The pipeline I sent is not in our samples, that pipeline is for my development purpose, it is too complicated as a sample. You can build your own pipeline based on modifying it.

If you just want to use LibreFace to open mp4 files and get its outputs, there is a branch called dev-libreface-app. In that branch, we have a console application that can do that. Though that is only the very first version and I am still working on its compatibility and serialization performance, you can try that and you do not need the OpenSense WPF Application.
